In [1]:
#Write a NumPy program to create an element-wise comparison (greater,
#greater_equal, less and less_equal) of two given arrays.
import numpy as np

x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])

print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Comparison - greater
[False False False False False False False False False False]
Comparison - greater_equal
[ True  True  True  True  True  True  True  True  True False]
Comparison - less
[False False False False False False False False False  True]
Comparison - less_equal
[ True  True  True  True  True  True  True  True  True  True]


In [3]:
#Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

array1=np.zeros(10)
print("An array of 10 zeros:")
print(array1)
array2=np.ones(10)
print("An array of 10 ones:")
print(array2)
array3=np.ones(10)*5
print("An array of 10 fives:")
print(array3)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [18]:
#3.	Write a NumPy program to generate a random number between 0 and 1
import numpy as np 
#random.random return number in range 0-1
rand_num = np.random.random()

print(np.random.random(3))
#random.uniform return float between # to #
print(np.random.uniform(5,6))

#randint(low, high, size, dtype=int)
#size - array(row,col)
print(np.random.randint(10,size=(10)))
print(np.random.randint(10,20,size=(3,10)))

Random number between 0 and 1:
[-0.57116892 -0.65042062  0.03214388  0.22273205]


In [19]:
#4.	Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
print(np.random.randint(10,22,size=(3,4)))

[[21 11 19 17]
 [11 21 21 16]
 [10 14 20 20]]


In [20]:
'''
5.	Write a NumPy program to convert an array to a float type. 
Sample output:
Original array
[1, 2, 3, 4]
'''
a = np.array([1, 2, 3, 4])
print(a.astype(np.float32))
x = np.asfarray(a)
print(x)

[1. 2. 3. 4.]
[1. 2. 3. 4.]


In [21]:
#6.	Write a NumPy program to convert a list and tuple into arrays
l = [1, 2, 3, 4]
t = (1,2,3,4)
n = np.array(l) #makes a copy
n[0] = 11
print(l)
print(n)

n2 = np.asarray(l) #will not make copy unless necessary
n2[0] = 12
print(l)
print(n2)
print(n.dtype == n2.dtype)

tp = np.array(t)
print(tp)
tp2 = np.asarray(t)
print(tp2)

[1, 2, 3, 4]
[11  2  3  4]
[1, 2, 3, 4]
[12  2  3  4]
True
[1 2 3 4]
[1 2 3 4]


In [22]:
#7.	Write a NumPy program to find common values between two arrays.  
#Array1: [ 0 10 20 40 60]
#Array2: [10, 30, 40]
a1 =  np.array([ 0, 10, 20, 40, 60])
a2 = np.array([10, 30, 40])
print(np.intersect1d(a1,a2))

[10 40]


In [24]:
'''8.	Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.  
Original array: [1 2 3 4 5 6]'''
a3 = np.array([1, 2, 3, 4, 5, 6])
print("Maximum Values index: ",np.max(a3))
print("Maximum Values : ",np.argmax(a3))
print("Minimum Values index: ",np.argmin(a3))

Maximum Values index:  6
Maximum Values :  5
Minimum Values index:  0


In [2]:
#9.	Write a NumPy program to compute the determinant of a given square array.
# determinant is a value that can be computed from the elements of a square matrix.
# https://www.youtube.com/watch?v=Ip3X9LOh2dk
from numpy import linalg as LA  #import linear algebra
a = np.array([[1,3], [3,6]]) 
print(np.linalg.det(a))

-3.0000000000000004


In [3]:
 #10.	Write a NumPy program to compute the multiplication of two given matrixes.
c =  np.array([[1,2],[2,1]] )
d = np.array([[2,2],[2,1] ])
print(np.dot(c,d))

[[6 4]
 [6 5]]


In [17]:
oa = [(b'James', 5, 48.5 ), (b'Nail', 6, 52.5 ), (b'Paul', 5, 42.1 ), (b'Pit', 5, 40.11)]
oa
print(np.shape(oa))
np.size(oa)



(4, 3)


12

In [24]:
#Write a NumPy program to create a structured array from given
#student name, height, class and their data types. Now sort the array on
#height.
#I DONT REALLY GET THIS, ESPECIALLY THE s10, s15 whatever thing

data_type = [('name', 'S10'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by height")
print(np.sort(students, order='height'))   

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


In [30]:
#Write a NumPy program to get the indices of the sorted elements of
#a given array. 
#Original array:
#[1023 5202 6230 1671 1682 5241 4532]

num_array = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("Original array:")
print(num_array)
i = np.sort(num_array)
h = np.argsort(num_array)
print("Indices of the sorted elements of a given array:")
print(h)
print("Sorted array: ")
print(i) #sorted version

Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]
Sorted array: 
[1023 1671 1682 4532 5202 5241 6230]


In [39]:
#Write a NumPy program to concatenate element-wise two arrays of string. 
#Array1:
#['Python''PHP']
#Array2:
#['Java''C++'']

x1 = np.array(['Python', 'PHP']) #x1 = np.array(['Python', 'PHP'], dtype=str) secifies type for some reason
x2 = np.array([' Java', ' C++'])
print("Array1:")
print(x1)
print("Array2:")
print(x2)
new_array = np.char.add(x1, x2)
print("new array:")
print(new_array)


print("Concatenate looks like this but it's not the answer here: ")
print(np.concatenate((x1, x2)))

Array1:
['Python' 'PHP']
Array2:
[' Java' ' C++']
new array:
['Python Java' 'PHP C++']
Concatenate looks like this but it's not the answer here: 
['Python' 'PHP' ' Java' ' C++']


In [44]:
#Write a NumPy program to repeat all the elements three times of a
#given array of string 
#Expected Output:
#Original Array:
#['Python' 'PHP' ' Java' ' C++']

x1 = np.array(['Python', 'PHP', 'Java', 'C++'])
print("Original Array:")
print(x1)
new_array = np.char.multiply(x1, 3)
print("New array:")
print(new_array)
print("np.repeat():\n", np.repeat(x1,3))
print("\nnp.transpose():\n",np.transpose([x1] * 3))

Original Array:
['Python' 'PHP' 'Java' 'C++']
New array:
['PythonPythonPython' 'PHPPHPPHP' 'JavaJavaJava' 'C++C++C++']
np.repeat():
 ['Python' 'Python' 'Python' 'PHP' 'PHP' 'PHP' 'Java' 'Java' 'Java' 'C++'
 'C++' 'C++']

np.transpose():
 [['Python' 'Python' 'Python']
 ['PHP' 'PHP' 'PHP']
 ['Java' 'Java' 'Java']
 ['C++' 'C++' 'C++']]


In [45]:
#Write a NumPy program to split the element of a given array with
#spaces. 
#Original Array:
#['Python PHP Java C++']

pArray =  np.array(['Python PHP Java C++'])
pArray2 =  np.array(['Python, P,H,P, Java, C++'])

print(np.char.split(pArray))
print(np.char.split(pArray2, ",")) #without whitespace #trying without writing sep=
print(np.char.split(pArray2, sep=", ")) #with whitespace

[list(['Python', 'PHP', 'Java', 'C++'])]
[list(['Python', ' P', 'H', 'P', ' Java', ' C++'])]
[list(['Python', 'P,H,P', 'Java', 'C++'])]
