In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [7]:
print(a[0], a[1], a[2])
print(a[0], a[2])

1 2 3
1 3


In [8]:
a[0] = 5
print(a)

[5 2 3]


In [11]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0], b[0,1], b[1,0])
print(b[1,1])

(2, 3)
1 2 4
5


In [23]:
#creating an array of only zeros
a = np.zeros((2,2))
print(a)
print(a.dtype)
print(a.shape)
print(a.size)
print(a.ndim)
b6 = np.zeros((1,2))
print(b6)


[[0. 0.]
 [0. 0.]]
float64
(2, 2)
4
2
[[0. 0.]]


In [13]:
#creating array of all ones
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [18]:
#create an array of same values, 7 in this case
c = np.full((2,2), 7)
print(c)
print(c.dtype)

[[7 7]
 [7 7]]
int32


In [20]:
#create 2x2 identity matrix - diagonals are 1s, surroundings are 0s
#only works when same number of rows and columns so only takes 1 value
d = np.eye(2)
print(d)
print(d.dtype)

[[1. 0.]
 [0. 1.]]
float64


In [28]:
#array with random value
e = np.random.random((2,2))
print(e)

[[1.00124132e-04 4.15757961e-01]
 [3.25569660e-01 8.26928957e-01]]


In [81]:
#create rank 2 array 3x4
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
#slicing to pull out subarray 
####ASK ABOUT THIS
b = a[0:1, 1:2]
print(b)
#mean 0,2 to 1,3 which is actually 0,1 to 1,2 becaus python doesnt take the last number

[[2]]


In [41]:
#modifying the slice will modify the original array too
c = a[:2, 1:3]
print(c)
print(a[0,0])
c[0,0] = 77
print(a[0,1])

#since c(0,0) is the same place as a(0,1) the values are now changed in both

[[2 3]
 [6 7]]
1
77


In [51]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x, '\n')
print(y,'\n')
# Elementwise sum; both produce the array

print(x + y)

#print(np.add(x, y))

[[1. 2.]
 [3. 4.]] 

[[5. 6.]
 [7. 8.]] 

[[ 6.  8.]
 [10. 12.]]


In [54]:
# Elementwise difference; both produce the array
print(x, '\n')
print(y,'\n')
print(x - y)
#print(np.subtract(x, y))

[[1. 2.]
 [3. 4.]] 

[[5. 6.]
 [7. 8.]] 

[[-4. -4.]
 [-4. -4.]]


In [58]:
# Elementwise product; both produce the array
#Not matrix multiplication, but useful for image processing applications

print(x, '\n')
print(y,'\n')
print(x * y)
#print(np.multiply(x, y))

[[1. 2.]
 [3. 4.]] 

[[5. 6.]
 [7. 8.]] 

[[ 5. 12.]
 [21. 32.]]


In [66]:
#columns # of a has to equal row number of b to be able to multiply
#reultant is row number of a and column number of b
f = np.dot(x,y) #this is matrix multiplication
print(f)

[[19. 22.]
 [43. 50.]]


In [67]:
g = np.matmul(x,y) #another way I think to get matrix multiplication
print(g)

[[19. 22.]
 [43. 50.]]


In [64]:
print(f.dtype)

float64


In [65]:
print(g.dtype)

float64


In [75]:
h = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
j = np.array([[2,4,6],[3,5,7], [1,4,8],[3,4,2]])

print(h)
print(j)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 4 6]
 [3 5 7]
 [1 4 8]
 [3 4 2]]


In [76]:
np.matmul(h, j)

array([[ 23,  42,  52],
       [ 59, 110, 144],
       [ 95, 178, 236]])

In [77]:
np.dot(h,j)

array([[ 23,  42,  52],
       [ 59, 110, 144],
       [ 95, 178, 236]])

In [78]:
np.multiply(h,j)

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [2]:
a1=np.array([0,1,7,3, 7])
a1.dtype

dtype('int32')

In [3]:
type(a1)

numpy.ndarray

In [6]:
c1=np.array([20,1,2,3,4])

c1[0]=100

c1
c1[0]=2
c1

array([2, 1, 2, 3, 4])

In [7]:
2*c1

array([4, 2, 4, 6, 8])

In [8]:
c1.shape

(5,)

In [9]:
c1.size

5

In [34]:
a3=np.array([0,1])
b3=np.array([1,0])
print(a3)
print(b3)
print(a3.size)
print(a3.shape)
print(b3.shape)

np.dot(a3,b3)

#I dont get it

[0 1]
[1 0]
2
(2,)
(2,)


0

In [35]:
with open("Example1.txt","r") as file1:
  
    FileContent=file1.read()
    
    print(FileContent)

This is line 1

This is line 2

This is line 3
