# NUMPY

![](numpy1.png)

### Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

#### A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
#### The number of dimensions is the rank of the array; 
#### The shape of an array is a tuple of integers giving the size of the array along each dimension.

![](numpy.png)

In [1]:
import numpy as np

##### Create a rank 1 array

In [2]:
a = np.array([1, 2, 3])   
a          

array([1, 2, 3])

##### Type & Shape

In [3]:
print(type(a)) 
print(a.shape)            

<class 'numpy.ndarray'>
(3,)


In [4]:
print(a[0], a[1], a[2])   

1 2 3


##### Changing array element

In [5]:
a[0] = 5                  
print(a)                  

[5 2 3]


##### Create a rank 2 array

In [6]:
b = np.array([[1,2,3],[4,5,6]])    
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])   

(2, 3)
1 2 4


##### Create an array of all zeros

In [30]:
a = np.zeros((2,2))   
print(a)       
print(a.dtype)         

[[0. 0.]
 [0. 0.]]
float64


##### Create an array of all ones

In [8]:
b = np.ones((1,2))    
print(b)              

[[1. 1.]]


##### Create a constant array

In [9]:
c = np.full((2,2), 7)   
print(c)
print(c.dtype)         

[[7 7]
 [7 7]]
int32


##### Create a 2x2 identity matrix

In [10]:
d = np.eye(2)          
print(d)              

[[1. 0.]
 [0. 1.]]


##### Create an array filled with random values

In [11]:
e = np.random.random((2,2))   
print(e)                     

[[0.6862616  0.39167602]
 [0.33658566 0.99594427]]


### Array indexing

#### Numpy offers several ways to index into arrays.

#### Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

##### Create the following rank 2 array with shape (3, 4)

In [32]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
b = a[:2, 1:3]
print(b)


[[2 3]
 [6 7]]


In [34]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
b = a[:2, 1:3]
print(a[0, 0])   
b[0, 0] = 77     
print(a[0, 1])   

1
77


In [15]:
# Create the following rank 2 array with shape (3, 4)

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [16]:
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  
print(row_r2, row_r2.shape)  

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [17]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  
print(col_r2, col_r2.shape)  

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Datatypes

#### Every numpy array is a grid of elements of the same type. 
#### Numpy provides a large set of numeric datatypes that you can use to construct arrays. 
#### Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype.

In [18]:
x = np.array([1, 2])   
print(x.dtype)         

x = np.array([1.0, 2.0])   
print(x.dtype)             

x = np.array([1, 2], dtype=np.int64)   
print(x.dtype)                         

int32
float64
int64


### Array math

In [19]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array

print(x + y)

print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [20]:
# Elementwise difference; both produce the array

print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


![](numpy-matrix-product.png)

In [21]:
# Elementwise product; both produce the array


print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [22]:
# Elementwise division; both produce the array

print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [23]:
# Elementwise square root; produces the array

print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


##### Assigning x,y,v&w

In [24]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [25]:
# Inner product of vectors
print(v.dot(w))
print(np.dot(v, w))

219
219


In [26]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [27]:
# Matrix / matrix product; both produce the rank 2 array

print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### SUM FUNCTION

In [28]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; 
print(np.sum(x, axis=0))  # Compute sum of each column; 
print(np.sum(x, axis=1))  # Compute sum of each row; 

10
[4 6]
[3 7]


## Arithmetic Operations:

#### Addition: np.add(a,b)
#### Subtraction:np.subtract(a,b)
#### Multiplication: np.multiply(a,b)
#### Division: np.divide(a,b)
#### Exponentiation: np.exp(a)
#### Square Root: np.sqrt(b)


### Comparison
#### Element-wise: a==b
#### Array-wise: np.array_equal(a,b)

### Copying:
#### np.copy(array) – Copies array to new memory array.
#### view(dtype) – Creates view of array elements with typedtype

### Sorting:
#### array.sort() – Sorts array
#### array.sort(axis=0) – Sorts specific axis of array
#### array.reshape(2,3) – Reshapes array to 2 rows, 3 columns without changing data.

### Adding:
#### np.append(array,values) – Appends values to end of array
#### np.insert(array,4,values) – Inserts values into array before index 4

### Removing:
#### np.delete(array,2,axis=0) – Deletes row on index 2 of array
#### np.delete(array,3,axis=1) – Deletes column on index 3 of array

### Combining:
#### np.concatenate((array1,array2),axis=0) – Adds array2 as rows to the end of array1
#### np.concatenate((array1,array2),axis=1) – Adds array2 as columns to end of array1

### Splitting:
#### np.split(array,3) – Splits array into 3sub-arrays

### Indexing:
#### a[0]=5 – Assigns array element on index 0 the value 5
#### a[2,3]=1 – Assigns array element on index [2][3] the value 1

### Subsetting:
#### a[2]: Returns the element of index 2 in array a.
#### a[3,5] – Returns the 2D array element on index [3][5]

### Slicing:
#### a[0:4] – Returns the elements at indices 0,1,2,3
#### a[0:4,3] – Returns the elements on rows 0,1,2,3 at column 3
#### a[:2] – Returns the elements at indices 0,1
#### a[:,1] – Returns the elements at index 1 on all rows

In [29]:
#https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md